# Generated by Django 4.1.6 on 2023-02-11 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('descriptions', models.CharField(max_length=150)),
                ('Video_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=150)),
                ('descriptions', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='BannerImage')),
                ('url_http_link', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='Brand_section_Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100, null=True)),
                ('logo', models.ImageField(upload_to='BrandSectionIogo')),
                ('company_link', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': ' Brand_section',
                'verbose_name_plural': ' Brand_sections',
            },
        ),
        migrations.CreateModel(
            name='Fact_counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Fact_counter',
                'verbose_name_plural': 'Fact_counters',
            },
        ),
        migrations.CreateModel(
            name='Footer_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='News_sectionImage')),
                ('detalis', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('facebook_link', models.CharField(blank=True, max_length=150, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=150, null=True)),
                ('google_plus_link', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Footer_section',
                'verbose_name_plural': 'Footer_sections',
            },
        ),
        migrations.CreateModel(
            name='I_Gave_Protection_L',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'I_Gave_Protection_L',
                'verbose_name_plural': 'I_Gave_Protections_L',
            },
        ),
        migrations.CreateModel(
            name='I_Gave_Protection_R',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'I_Gave_Protection_R',
                'verbose_name_plural': 'I_Gave_Protections_R',
            },
        ),
        migrations.CreateModel(
            name='News_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='News_sectionImage')),
                ('title', models.CharField(max_length=100)),
                ('detalis', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=100, null=True)),
                ('url_http_link', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'News_section',
                'verbose_name_plural': 'News_sections',
            },
        ),
        migrations.CreateModel(
            name='Other_Page_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Other_Image')),
                ('Image_Name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Other_Page_Images',
            },
        ),
        migrations.CreateModel(
            name='Security_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='SecurityInformationImage')),
                ('top_text', models.CharField(max_length=100, null=True)),
                ('information_title', models.CharField(max_length=500, null=True)),
                ('detalis', models.CharField(max_length=550, null=True)),
            ],
            options={
                'verbose_name': 'Security_information',
                'verbose_name_plural': 'Security_informations',
            },
        ),
        migrations.CreateModel(
            name='Service_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ServiceImage')),
                ('title', models.CharField(max_length=100)),
                ('detalis', models.CharField(max_length=150)),
                ('url_http_link', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('skill_level', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Team_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='SecurityInformationImage')),
                ('name', models.CharField(max_length=100)),
                ('titel', models.CharField(max_length=100)),
                ('detalis', models.CharField(max_length=250)),
                ('facebook_link', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=150, null=True)),
                ('google_plus_link', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Team_section',
                'verbose_name_plural': 'Team_sections',
            },
        ),
        migrations.CreateModel(
            name='Testimonial_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='TestimonialSectionImage')),
                ('name', models.CharField(max_length=100)),
                ('titel', models.CharField(max_length=100)),
                ('detalis', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Testimonial_section',
                'verbose_name_plural': 'Testimonial_sections',
            },
        ),
        migrations.CreateModel(
            name='Contat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('satet', models.CharField(max_length=150)),
                ('massege', models.CharField(max_length=500)),
                ('topics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_app.service_section')),
            ],
            options={
                'verbose_name': 'contat',
                'verbose_name_plural': 'contats',
            },
        ),
    ]
