# Generated by Django 4.1.6 on 2023-02-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Our_blogImage')),
                ('title', models.CharField(max_length=100)),
                ('detalis', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Our_blog',
                'verbose_name_plural': 'Our_blogs',
            },
        ),
        migrations.RemoveField(
            model_name='news_section',
            name='url_http_link',
        ),
        migrations.RemoveField(
            model_name='service_section',
            name='url_http_link',
        ),
        migrations.AlterField(
            model_name='footer_section',
            name='image',
            field=models.ImageField(upload_to='Our_blog'),
        ),
    ]
