# Generated by Django 4.1.6 on 2023-02-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0002_our_blog_remove_news_section_url_http_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board_of_directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='BoardOfDirectors')),
                ('first_detalis', models.TextField(blank=True)),
                ('last_detalis', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Board_of_directors',
                'verbose_name_plural': 'Board_of_directorss',
            },
        ),
    ]
