# Generated by Django 4.1.6 on 2023-02-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0004_rename_first_detalis_board_of_directors_first_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_of_directors',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
