# Generated by Django 4.1.6 on 2023-02-17 06:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0006_remove_about_descriptions_remove_banner_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='descriptions',
            field=ckeditor.fields.RichTextField(default='aaa'),
        ),
        migrations.AddField(
            model_name='banner',
            name='descriptions',
            field=ckeditor.fields.RichTextField(default='aaa'),
        ),
        migrations.AddField(
            model_name='board_of_directors',
            name='first_part',
            field=ckeditor.fields.RichTextField(default='aaa'),
        ),
        migrations.AddField(
            model_name='board_of_directors',
            name='secend_part',
            field=ckeditor.fields.RichTextField(default='aaa'),
        ),
    ]
