# Generated by Django 4.1.6 on 2023-02-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0008_management_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_clicnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Our_clicntImage')),
                ('company_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Our_clicnt',
                'verbose_name_plural': 'Our_clicnts',
            },
        ),
    ]
