# Generated by Django 4.1.6 on 2023-02-18 10:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0010_clicnts_testimonials_contract_signing_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='NewsImage')),
                ('news_title', models.CharField(max_length=150)),
                ('news_date', models.CharField(max_length=150)),
                ('news_details', ckeditor.fields.RichTextField(default='aaa')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'Newss',
            },
        ),
        migrations.AlterModelOptions(
            name='contract_signing',
            options={'verbose_name': 'Contract_signing', 'verbose_name_plural': 'Contract_signings'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'History', 'verbose_name_plural': 'Historys'},
        ),
    ]
