# Generated by Django 4.1.6 on 2023-02-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0011_news_alter_contract_signing_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='News_add_page',
        ),
        migrations.AlterModelOptions(
            name='news_add_page',
            options={'verbose_name': 'News_add_page', 'verbose_name_plural': 'News_add_page'},
        ),
    ]
