# Generated by Django 4.1.6 on 2023-02-19 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0013_csr_add_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News_add_page',
        ),
    ]
