# Generated by Django 4.1.6 on 2023-02-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0014_delete_news_add_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Photo_gallery',
                'verbose_name_plural': 'Photo_gallerys',
            },
        ),
        migrations.CreateModel(
            name='Video_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_head_line', models.CharField(max_length=100)),
                ('video_thumbnail', models.CharField(max_length=100, null=True)),
                ('videofile', models.FileField(null=True, upload_to='Video_gallery/')),
            ],
            options={
                'verbose_name': 'Video_gallery',
                'verbose_name_plural': 'Video_gallerys',
            },
        ),
    ]
