# Generated by Django 4.1.6 on 2023-02-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0015_photo_gallery_video_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_gallery',
            name='image',
            field=models.ImageField(null=True, upload_to='Photo_galleryImage/'),
        ),
        migrations.AlterField(
            model_name='video_gallery',
            name='video_thumbnail',
            field=models.ImageField(null=True, upload_to='Photo_galleryThumbnail/'),
        ),
    ]
