# Generated by Django 4.1.6 on 2023-02-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0016_alter_photo_gallery_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_gallery',
            name='videofile',
        ),
        migrations.AddField(
            model_name='video_gallery',
            name='video_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='video_gallery',
            name='video_head_line',
            field=models.CharField(max_length=50),
        ),
    ]
