# Generated by Django 4.1.6 on 2023-02-20 06:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0018_job_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='job_details',
            field=ckeditor.fields.RichTextField(default='aaa'),
        ),
        migrations.AlterField(
            model_name='management_term',
            name='profile_details',
            field=ckeditor.fields.RichTextField(default='aaa'),
        ),
        migrations.AlterField(
            model_name='photo_gallery',
            name='details',
            field=ckeditor.fields.RichTextField(default='aaa'),
        ),
    ]
