# Generated by Django 4.1.6 on 2023-02-20 09:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0019_job_post_job_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header_and_Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Our_blog')),
                ('detalis', models.CharField(max_length=150)),
                ('phone_number1', models.CharField(max_length=16)),
                ('phone_number2', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('facebook_link', models.CharField(blank=True, max_length=150, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=150, null=True)),
                ('google_plus_link', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Footer_section',
                'verbose_name_plural': 'Footer_sections',
            },
        ),
        migrations.DeleteModel(
            name='Footer_section',
        ),
        migrations.AlterField(
            model_name='service_section',
            name='detalis',
            field=ckeditor.fields.RichTextField(default='aaa'),
        ),
    ]
