# Generated by Django 4.1.6 on 2023-02-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0020_header_and_footer_delete_footer_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header_and_footer',
            options={'verbose_name': 'Header_and_Footer', 'verbose_name_plural': 'Header_and_Footers'},
        ),
        migrations.RemoveField(
            model_name='header_and_footer',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='header_and_footer',
            name='google_plus_link',
        ),
        migrations.RemoveField(
            model_name='header_and_footer',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='header_and_footer',
            name='twitter_link',
        ),
    ]
