# Generated by Django 4.1.6 on 2023-02-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0021_alter_header_and_footer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand_section_add',
            options={'verbose_name': ' Brand_section_Add', 'verbose_name_plural': ' Brand_section_Adds'},
        ),
        migrations.RenameField(
            model_name='brand_section_add',
            old_name='c_name',
            new_name='Company_Name',
        ),
        migrations.RemoveField(
            model_name='brand_section_add',
            name='company_link',
        ),
    ]
