# Generated by Django 4.1.6 on 2023-02-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0023_social_media_delete_our_clicnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_media',
            name='company_name',
            field=models.URLField(max_length=80),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='google_plus_link',
            field=models.URLField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=80),
        ),
    ]
