# Generated by Django 4.1.6 on 2023-02-25 05:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0025_alter_social_media_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='HistoryImage')),
                ('job_Details', ckeditor.fields.RichTextField(default='aaa')),
            ],
            options={
                'verbose_name': 'job_Details',
                'verbose_name_plural': 'job_Detailss',
            },
        ),
    ]
