# Generated by Django 4.1.6 on 2023-02-25 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0026_job_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job_details',
            options={'verbose_name': 'Job_Details', 'verbose_name_plural': 'Job_Detailss'},
        ),
    ]
