# Generated by Django 4.1.6 on 2023-02-25 07:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0027_alter_job_details_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='job_Details',
        ),
        migrations.AddField(
            model_name='job_post',
            name='job_banner_image',
            field=models.ImageField(null=True, upload_to='JobBannerImage'),
        ),
        migrations.AlterField(
            model_name='job_post',
            name='job_details',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
