# Generated by Django 4.1.6 on 2023-02-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0028_delete_job_details_job_post_job_banner_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=150)),
                ('massege', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Apply_form',
                'verbose_name_plural': 'Apply_forms',
            },
        ),
    ]
